[build]
  command = "npm run build --workspace baakh-nextjs"
  publish = "baakh-nextjs/.next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

