name: Cloudflare Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check for Wrangler config
        id: check-wrangler
        run: |
          if [ -f "baakh-nextjs/wrangler.jsonc" ] || [ -f "baakh-nextjs/wrangler.toml" ]; then
            echo "has_config=true" >> $GITHUB_OUTPUT
          else
            echo "has_config=false" >> $GITHUB_OUTPUT
          fi

      - name: Skip deploy (no wrangler config found)
        if: steps.check-wrangler.outputs.has_config == 'false'
        run: |
          echo "No wrangler.jsonc or wrangler.toml found in baakh-nextjs; skipping Cloudflare deploy." >> $GITHUB_STEP_SUMMARY

      - name: Install deps (baakh-nextjs)
        if: steps.check-wrangler.outputs.has_config == 'true'
        working-directory: baakh-nextjs
        run: npm install --no-audit --no-fund

      - name: Deploy to Cloudflare with Wrangler (Pages)
        if: steps.check-wrangler.outputs.has_config == 'true'
        working-directory: baakh-nextjs
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npm run build:pages && npx wrangler pages deploy ./.vercel/output/static --project-name=${{ secrets.CLOUDFLARE_PAGES_PROJECT }} --branch=${{ github.ref_name }}

