[build]
  # Base directory for the build
  base = "."
  
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory (Next.js default output)
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Next.js specific environment variables
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=()"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions directory (if you have any Netlify functions)
[functions]
  directory = "netlify/functions"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

